image: node:6.9.2

cache:
  paths:
   - node_modules/

before_script:
 - npm config set strict-ssl false
 - npm config set cache-min 999999
 - npm config set registry "http://registry.npmjs.org/"
 - npm install

test:
  script:
    - npm run build
